# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-10 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutoriales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('capitulo', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
