# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-11 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoriales',
            name='video',
        ),
        migrations.AddField(
            model_name='tutoriales',
            name='direccion',
            field=models.URLField(blank=True, null=True),
        ),
    ]
