# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-11 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriales', '0003_tutoriales_descarga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descargas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('direccion', models.URLField(blank=True, null=True)),
                ('capitulo', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
